Homework 1
slfdstrctd/ml-system-design pull request #1
Opened 2024-11-27 14:30 UTC by slfdstrctd

- Add poetry, precommit with linters
- Add `docs/ml_system_design_doc.md` with description of project

2024-11-28 15:22 UTC, konstantgr commented
**Сетап репозитория проекта**
- [x] Создать репозиторий на гитхабе
- [x] Подготовить репозиторий для работы в нем (3/3):
  - [x] настроить линтеры и форматеры (ruff, black) (1/1)
  - [x] настроить pre-commit (1/1)
  - [x] заполнить файл readme.md с основной информацией о проекте (1/1)

**Заполнение дизайн-документа**
- [x] Создать в репозитории папку docs
- [x] В папке /docs создать файл ml_system_design_doc.md При создании файла можно ориентироваться на структуру [шаблона] (7/7)
  - [x] Зачем идем в разработку продукта? (1/1)
  - [x] Бизнес-требования и ограничения (2/2)
  - [x] Что входит в скоуп проекта/итерации, что не входит (1/1)
  - [x] Предпосылки решения (1/1)
  - [x] Постановка задачи (1/1)
  - [x] Блок-схема решения (1/1)

Итого: `10/10`

2024-12-02 08:56 UTC, halfpast-learn approved these changes
Согласен с konstantgr, все критерии соблюдены, разве что не хватает пустой линии в yaml и toml файлах, гитхаб подсвечивает. 10/10.

2024-12-17 14:41 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! В целом все хорошо, но хочется подчеркнуть, что в дизайн-доке мы не описываем готовое решение, а поэтапно проектируем новое, поэтому от всех методов/фреймворков/моделей как минимум стоит пока абстрагироваться и вводить из вместе с обоснованием, постепенно выстраивая процесс моделирования

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Salary prediction model using CatBoost
Несколько странно на этапе проектирования решения сразу видеть catboost... Возможно, у вас уже есть все готовое решение именно с этим фреймворком, но мы делаем дизайн "с нуля", а не натягиваем дизайн-додк на то, что есть... На данном этапе без какого-либо анализа в реальной жизни вы еще не можете знать, какая именно модель будет в проде, будет ли это вообще модель и т.п.

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Streamlit-based web interface
Опять же, это пока бизнес-требования. Можно представить для простоты, что их пишет менеджер - как правило, они не оперируют ML-терминологией, названиями фреймворков (да и не особо им это нужно), поэтому мы описываем, что входит в бизнесовый скоуп - MVP с web UI,  сегментация соискателей по навыкам и позициям и т.п.

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +- Pre-trained FastText model for Russian language
Опять же сравнение и выбор модели идет уже в DS-части в другом блоке, в бизнес-требованиях про FastText говорить рано, и, по-хорошему, его выбор надо обосновывать...

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +   - Metric: MAE (Mean Absolute Error) < 15000
У нас пока в этом ДЗ не было требований к метрикам, но выбор метрик и функций потерь требует отдельного обоснования

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +   - Metric: Silhouette score > 0.6
И здесь аналогично

2024-12-17 14:41 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +## 6. Solution Architecture
Опять же это уже схема готового решения, а части с бейзлайнами и выбором модели отсутствуют, поэтому это не концептуальная блок-схема работы над решением, а схема из пунктов про DS-часть.

Также если пока анализировать саму схему, то в ней смешаны разные типы сущностей, поэтому не очень понятно ее назначение - есть и данные, и модели, и компоненты MLOps-инфраструктуры, и процессы... Для оформления подобных схем стоит выбрать определенную нотацию, например, UML или C4, и следовать им, либо хотя бы концептуально разнести сущности по смыслу в разные схемы для очерчивания границ систем и процессов

2024-12-17 16:02 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +- Salary prediction model using CatBoost
Убрал упоминания конкретной модели

2024-12-17 16:04 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +- Streamlit-based web interface
Убрал упоминания фреймворка, перефразировал про кластеризацию

2024-12-17 16:04 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +- Pre-trained FastText model for Russian language
Убрал упоминания конкретной модели

2024-12-17 16:06 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +   - Metric: MAE (Mean Absolute Error) < 15000
Убрал про метрики в этом ДЗ, буду обосновывать на следующих этапах. 
Упоминание конкретной модели тоже убрал.

2024-12-17 16:06 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +   - Metric: Silhouette score > 0.6
Убрал конкретную метрику

2024-12-17 16:08 UTC, slfdstrctd commented on docs/ml_system_design_doc.md
> +## 6. Solution Architecture
Разбил диаграмму на две. Подумаю про UML, пока удобнее делать в Mermaid.
Одну с конкретным флоу сервиса, вторая - с флоу обучения моделей.

2024-12-24 12:10 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу! Теперь все отлично!

2024-12-28 12:36 UTC, merged